version: '2'
services:

  api:
    image: retypeme/retypeme-backend:latest
    restart: always
    ports:
      - "8080:8080"
    build:
      dockerfile: ./Dockerfile-multi
      context: ./backend
    environment:
      APPLICATION_CORS_ALLOWED_ORIGINS: "*"

  ui:
    image: retypeme/retypeme-frontend:latest
    restart: always
    ports:
      - "3001:3000"
    build:
      dockerfile: ./Dockerfile
      context: ./frontend
    depends_on:
      - api