version: "2"
services:
  api:
    image: retypeme/retypeme-backend:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: "dev"
      JASYPT_ENCRYPTOR_PASSWORD: ${JASYPT_ENCRYPTOR_PASSWORD}

  ui:
    image: retypeme/retypeme-frontend:latest
    restart: always
    ports:
      - "3001:3000"
    depends_on:
      - api
