version: "2"
services:
  api:
    image: retypeme/retypeme-backend:latest
    restart: always
    ports:
      - "8080:8080"
#    build:
#      dockerfile: backend/Dockerfile
#      context: .
#      args:
#        REPOSITORY_TOKEN: ${REPOSITORY_TOKEN}
    environment:
      SPRING_PROFILES_ACTIVE: "dev,w3"
      JASYPT_ENCRYPTOR_PASSWORD: ${JASYPT_ENCRYPTOR_PASSWORD}
      SPRING_DATA_REDIS_PASSWORD: secret
    volumes:
      - ./.dev-conf:/config
    depends_on:
      - redis

  ui:
    image: retypeme/retypeme-frontend:latest
    restart: always
    ports:
      - "3001:3000"
#    build:
#      dockerfile: ./Dockerfile
#      context: ./frontend
#      args:
#        NEXT_PUBLIC_ENV_LOCAL_INFURA_AMOY_API_KEY: ${NEXT_PUBLIC_ENV_LOCAL_INFURA_AMOY_API_KEY}
#        NEXT_PUBLIC_API_DOMAIN: ${NEXT_PUBLIC_API_DOMAIN}
    depends_on:
      - api

  redis:
    image: redis:latest
    restart: always
    command: ["redis-server", "--requirepass", "secret"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  config:
    driver: local
  redis-data:
    driver: local
