version: '2'
services:

  api:
    image: retypeme/retypeme-backend:latest
    restart: always
    ports:
      - "8080:8080"
    build:
      dockerfile: backend/Dockerfile
      context: .
    environment:
      APPLICATION_CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://localhost:3001"

  ui:
    image: retypeme/retypeme-frontend:latest
    restart: always
    ports:
      - "3001:3000"
    build:
      dockerfile: ./Dockerfile
      context: ./frontend
    depends_on:
      - api
