version: '2'
services:

  api:
    image: t0lia/retypeme-backend:latest
    restart: always
    ports:
      - "8080:8080"
    build:
      dockerfile: ./Dockerfile-multi
      context: ./backend
    environment:
      APPLICATION_CORS_ALLOWED_ORIGINS: "http://localhost:3001/,http://localhost:3000/"

  ui:
    image: t0lia/retypeme-frontend:latest
    restart: always
    ports:
      - "3001:3000"
    build:
      dockerfile: ./Dockerfile
      context: ./frontend
    environment:
      API_HOST: "app"
      API_PORT: "8080"
    depends_on:
      - api