# production
FROM amazoncorretto:17
#FROM amazoncorretto:21-alpine3.16
EXPOSE 8080
COPY  ./build/libs/backend-0.0.1-SNAPSHOT.jar app.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]