FROM gradle:8.4.0-jdk21 AS GRADLE_TOOL_CHAIN
WORKDIR /app
COPY build.gradle settings.gradle /app/
COPY src /app/src
RUN gradle clean build

FROM amazoncorretto:21
COPY --from=GRADLE_TOOL_CHAIN /app/build/libs/backend-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8080
CMD ["java", "-jar", "app.jar"]
