### GET All Sessions
GET http://localhost:8080/
Accept: application/json

### GET Session by ID
GET http://localhost:8080/{id}
Accept: application/json

### POST Create Session
POST http://localhost:8080/
Content-Type: application/json

### GET Contract
GET http://localhost:8080/api/contract/chain
Accept: application/json

### GET Contract
GET http://localhost:8080/api/contract/chains
Accept: application/json


### GET Contract
GET http://localhost:8080/api/contract/address
Accept: application/json

### GET Contract
GET http://localhost:8080/api/contract/id
Accept: application/json

### GET Contract
GET http://localhost:8080/api/contract/name
Accept: application/json

### GET session by id
GET http://localhost:8080/api/sessions/79112
Accept: application/json

