---
- name: Get Gradle Version on Localhost
  hosts: localhost
  connection: local
  gather_facts: yes

  tasks:
    - name: Check Gradle version
      command: '../backend/gradlew -v'
      register: gradle_version_output

    - name: Print Gradle Version
      debug:
        msg: "{{ gradle_version_output.stdout_lines }}"
