---
- name: Run deploy contract
  hosts: uat
  gather_facts: yes

  tasks:
    - name: Debug profile variable
      debug:
        var: profile

    - name: ensure directory retypeme exists
      file:
        path: /home/wheel/retypeme
        state: directory
        mode: 0755

    - name: render docker-compose file
      template:
        src: templates/docker-compose.yml.j2
        dest: /home/wheel/retypeme/docker-compose.yml
        mode: 0644

