openapi: 3.0.0
info:
  title: Session API
  version: 1.0.0
paths:
  /sessions:
    get:
      summary: Get all sessions
      operationId: getAllSessions
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SessionResponse'
    post:
      summary: Create a new session
      operationId: createSession
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Players'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionResponse'
  /sessions/{id}:
    parameters:
      - name: id
        in: path
        required: true
        description: Session ID
        schema:
          type: string
    get:
      summary: Get session by ID
      operationId: getSessionById
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionResponse'
        '404':
          description: Not Found
  /statistics/{userId}:
    get:
      summary: Get user statistics by ID
      operationId: getUserStatistics
      parameters:
        - name: userId
          in: path
          required: true
          description: User ID
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserStatistic'
        '404':
          description: Not Found

components:
  schemas:
    JoinSessionRequest:
      type: object
      properties:
        id:
          type: string
        userId:
          type: string
    JoinSessionResponse:
      type: object
      properties:
        id:
          type: string
        userId:
          type: string
    SessionRequest:
      type: object
      properties:
        id:
          type: string
    SessionResponse:
      type: object
      properties:
        id:
          type: string
        chain:
          type: integer
        players:
          type: integer
    Players:
      type: object
      required:
        - players
      properties:
        players:
          type: integer
    UserJoinRequest:
      type: object
      properties:
        userId:
          type: string
    ProgressUpdateRequest:
      type: object
      properties:
        userId:
          type: string
        progress:
          type: integer
    ProgressUpdateResponse:
      type: object
      properties:
        userId:
          type: string
        progress:
          type: integer
    UserStatistic:
      type: object
      properties:
        userId:
          type: string
        completedDuels:
          type: integer
        averageSpeed:
          type: number
          format: double
        bestSpeed:
          type: number
          format: double
        wins:
          type: integer
        maxSpeed:
          type: number
          format: double
        topSpeeds:
          type: array
          items:
            type: number
            format: double
        firstDuelDate:
          type: string
          format: date
