server:
  port: 8080
  servlet:
    context-path: /api
    session:
      timeout: 1m
      cookie:
        http-only: true
        secure: true
management:
  info:
    git:
      mode: full
  endpoints:
    info:
      enabled: true
    web:
      exposure:
        include: "health,info"
      cors:
        allowed-methods: "*"
        allowed-headers: "*"
  endpoint:
    health:
      show-details: always

contract:
  address: "0x"
  private-key: "0x"
  network-url: ""
  chain-id: 1