contract:
  private-key: ENC(HJOJAqv46FaKe+EP8UDjpnb2j6OIeAqx4pmg2Wy51ef83FhEQJcjyKSgWB/nxvP7VHAlOfL7n9ojKohRJD/GKELrLPiO46vsp8DAqDBkMQxUpr/5i48WR7ihSZ3h4nhrcq58VMhuElnyFdhf07m/aQ==)
  apikey:
    infura: ENC(gRoG5skQ/eF7QPrux4WSukPwhscEnEe6tmxJyv3D0cAps7WY3cClcJwqN6W5vReyAaN9HceM0U2mEOffCSnM4gNKT/lzVI1RodU72xOomfw=)
    chainstack: ENC(hmXkq30AsMWQVcRI/H1UVk6GIfnf2TvRy4V4YucYr0iJP7Uus4NI2+Y6YBcsyV1TjY8GZuF8uLNO5lGWME3gU/iyrLB0hhglfN9Rp/4yRlY=)
  chains: 80002,168587773,534351

management:
  endpoints:
    web:
      cors:
        allowed-origins: "http://localhost:3000,http://localhost:3001"

application:
  cors:
    allowed-origins: "http://localhost:3000,http://localhost:3001"
