spring:
  main:
    banner-mode: "off"
logging:
  level:
    org.springframework: OFF
    com.ulisesbocchio: OFF

contract:
  chains: 80002,168587773,534351
  private-key: ENC(09T4XPHqjoowdRHneMK/4ezKgnZUXSRL41ulqjKZpvkmbbYR+dDUNm27uq1k+866/5oOqQaMZgze2gdwqh5eeU6ZBfdcAR2TsRs17MPXBKmw30zTe5ZcXasjdwrwghPFIpxSRxA9w57C5dmoNyw0/A==)
  network: "polygon-amoy"
  apikey:
    infura: ENC(uGP2BJGUcrC0pGXerZyqXAPXtL29WpS3XR71DALUgUTeOlLyo8Ai70Y0SIw+AsgkHQ90hCZS0uAo9BnI42YTm9rxv4Ng2WoGj7NXoquAbJk=)
    chainstack: ENC(bSI63sWWw+T7f+CGcflIPBV17i6WeiNJMCIcGSrgysUs0bPrPKGm4r0GYqFdA9tmnl183jguqD0jbA5fNXUXSuj/wMMKcvkchUAaAiQBqh4=)
