contract:
  address: "0xb3c33b58de859a5e06aff62c9d66319c256218da"
  private-key: ENC(4F38/ymuKeIPOMIEiKilkCT2n0PHroL+6cOvsqm3lQ851Ezv8WupESEdtrTkSw2p1USbnY/OO1Pdoq8w7PxzOnKenhDTYOCEBT+L06rQRkH6CWLncBBvuD3e9ualApPwQCFkvqlWsNUt09cG2ebdCw==)
  network: "polygon-amoy"
  apikey: ENC(maY86NPvqY1CtyH+l61AD0D5k7Y6Ao10VhuWuQMtAUJWPe3JrKC7HadriCSADShW7mOdwB809yZMMTLujZ6lgZQ4T9y+kaGo/R98ikQvZAE=)
  chain-id: 80002
management:
  endpoints:
    web:
      cors:
        allowed-origins: ENC(LOGbKP/v2VupGawEW4b5T1vIaGGNo3vT9G6TDqVnGUyc/rAcTaj+gZm8vHxqZKnoryv/1UqqzLHYfoNEvP3md5YTik3y9WuDWqXoRIXcaT5owWLC+Jn3+gx1wgKZ7fHO)
application:
  cors:
    allowed-origins: ENC(2qq/GumkzRZQR9gHpOVDGQCKcSMrb49sUYK6oLHnmD/1pPEdHOUeKeFtONflqTi+i7lg5SF9OyoXGCdBTxs+BZV8mugNh9FzGbA3RtcAEsjjMUyer4vtGyqnd3OpqACm)

