server:
  port: 8080
  servlet:
    context-path: /api
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
application:
  cors:
    allowed-origins: "http://localhost:3000/"