server:
  port: 8080
  servlet:
    context-path: /api
    session:
      timeout: 4320m
      cookie:
        http-only: true
        secure: true
        same-site: None
management:
  info:
    git:
      mode: full
  endpoints:
    info:
      enabled: true
    web:
      exposure:
        include: "health,info"
      cors:
        allowed-methods: "*"
        allowed-headers: "*"
  endpoint:
    health:
      show-details: always

contract:
  address: "0x"
  private-key: "0x"
  network-url: ""
  chain-id: 1
spring:
  cache:
    type: redis
  data:
    redis:
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
      host: redis
      port: 6379
      timeout: 2000
      database: 0