server:
  port: 8080
  servlet:
    context-path: /api
management:
  info:
    git:
      mode: full
  endpoints:
    info:
      enabled: true
    web:
      exposure:
        include: "health,info"
      cors:
        allowed-origins: "http://localhost:3000"
        allowed-methods: "*"
        allowed-headers: "*"
  endpoint:
    health:
      show-details: always
application:
  cors:
    allowed-origins: "http://localhost:3000"

contract:
  address: "0x"
  private-key: "0x"
  network-url: ""
  chain-id: 1