name: Build Kotlin Project

on:
  push:
    branches:
      - ci

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          file: ./backend/Dockerfile-multi
          push: false
          tags: your-docker-image-tag:latest

#      - name: Push Docker image to registry
#        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
#        uses: docker/build-push-action@v2
#        with:
#          context: .
#          file: backend/Dockerfile
#          push: true
#          tags: your-docker-image-tag:latest
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
