name: build

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker backend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./backend/Dockerfile
          push: false
          tags: retypeme/retypeme-backend:latest
          build-args: |
            REPOSITORY_TOKEN=${{ secrets.REPOSITORY_TOKEN }}

      - name: Build Docker frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: false
          tags: retypeme/retypeme-frontend-uat:latest
          build-args: |
            NEXT_PUBLIC_ENV_LOCAL_INFURA_AMOY_API_KEY=${{ secrets.NEXT_PUBLIC_ENV_LOCAL_INFURA_AMOY_API_KEY }}
            NEXT_PUBLIC_API_DOMAIN=${{ NEXT_PUBLIC_API_DOMAIN_UAT }}

      - name: Build Docker frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: false
          tags: retypeme/retypeme-frontend-prod:latest
          build-args: |
            NEXT_PUBLIC_ENV_LOCAL_INFURA_AMOY_API_KEY=${{ secrets.NEXT_PUBLIC_ENV_LOCAL_INFURA_AMOY_API_KEY }}
            NEXT_PUBLIC_API_DOMAIN=${{ NEXT_PUBLIC_API_DOMAIN_PROD }}
