name: Build Kotlin Project

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Display build number
        run: |
          echo "Build number: ${{ github.run_number }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile-multi
          push: true
          tags: retypeme/retypeme-backend:latest

      - name: Build and push Docker frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: retypeme/retypeme-frontend:latest

      - name: Call server endpoint
        run: |
          curl -X POST -u username:${{ secrets.WEBHOOK_PASSWORD }} http://apozdniakov.com:8090/restart_script
